# SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

general:
  use_uvloop: true
  logging:
    console:
      _type: console
      level: WARN

  telemetry:
    tracing:
      phoenix:
        _type: phoenix
        endpoint: ${PHOENIX_ENDPOINT}
        project: ai-virtual-assistant  
      dfw_elasticsearch:
        _type: nemo_dfw_elasticsearch
        endpoint: ${DATA_FLYWHEEL_ENDPOINT}
        client_id: ${DATA_FLYWHEEL_CLIENT_ID}
        index: flywheel

  front_end:
    _type: fastapi
    endpoints:
      - path: /create_session
        method: GET
        description: Generate a new session id.
        function_name: create_session
      - path: /end_session
        method: GET
        description: Ends the session for session id
        function_name: end_session
      - path: /delete_session
        method: GET
        description: Deletes session for session id.
        function_name: delete_session        
      - path: /health
        method: GET
        description: Validates the service is running.
        function_name: health_check      
      - path: /metrics
        method: GET
        description: Prometheus metrics for the service.
        function_name: prometheus_metrics   
      - path: /feedback/response
        method: POST
        description: Store user feedback for the last response in a conversation session.
        function_name: feedback_response                       

functions:
  create_session:
    _type: create_session
  end_session:
    _type: end_session    
  delete_session:
    _type: delete_session
  health_check:
    _type: health_check
  prometheus_metrics:
    _type: prometheus_metrics    
  feedback_response:
    _type: feedback_response
  get_product_name:
    _type: get_product_name
    llm_name: chat_llm    
  validate_product_info:
    _type: validate_product_info
  get_purchase_history:
    _type: get_purchase_history
    database_url: ${APP_DATABASE_URL}
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    dbname: ${CUSTOMER_DATA_DB}
  user_info:
    _type: user_info
  handle_product_qa:
    _type: handle_product_qa
    llm_name: chat_llm
  handle_other_talk:
    _type: handle_other_talk
    llm_name: chat_llm
  ask_clarification:
    _type: ask_clarification
    llm_name: chat_llm    

llms:
  tool_call_llm:
    _type: nim
    model_name: ${APP_TOOLCALL_LLM_MODELNAME}
    base_url: ${APP_TOOLCALL_LLM_SERVERURL}
    temperature: 0.2
    top_p: 0.7
    max_tokens: 1024    
    api_key: ${NVIDIA_API_KEY}
  chat_llm:
    _type: nim
    model_name: ${APP_CHAT_LLM_MODELNAME}
    base_url: ${APP_CHAT_LLM_SERVERURL}
    temperature: 0.2
    top_p: 0.7
    max_tokens: 1024    
    api_key: ${NVIDIA_API_KEY}    

workflow:
  _type: aiva_agent
  tool_call_llm_name: tool_call_llm
  chat_llm_name: chat_llm
